# -*- coding: utf-8 -*-
"""Customer Segmentation & Churn Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJdsFCL2_7TCcSwBaDXxsdOCOAQK2ETe
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

print("Shape:", df.shape)
df.info()

for col in df.columns:
    print(col)
    print(df[col].unique())
    print("-"*50)

df["Churn"] = df["Churn"].map({
    "Yes":1,
    "No":0
})

df["Churn"].value_counts()

df["gender"] = df["gender"].map({
    "Male":1,
    "Female":0
})

binary_cols = [
    "Partner",
    "Dependents",
    "PhoneService",
    "PaperlessBilling"
]

for col in binary_cols:
    df[col] = df[col].map({
        "Yes":1,
        "No":0
    })

df.head()

print(df.dtypes)

if 'customerID' in df.columns:
    df = df.drop('customerID', axis=1)
    print("customerID column dropped.")
else:
    print("customerID column not found, likely already dropped.")

df.head()

df = pd.get_dummies(df, drop_first=True)

print(df.shape)
print(df.dtypes)

bool_cols = df.select_dtypes(include='bool').columns

df[bool_cols] = df[bool_cols].astype(int)

print(df.dtypes)

print(df.shape)
df.head()

df["Churn"].value_counts()

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x="Churn", data=df)
plt.title("Customer Churn Distribution")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(), cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

segment_data = df[['tenure', 'MonthlyCharges', 'TotalCharges']]
segment_data.head()

scaler = StandardScaler()

scaled_data = scaler.fit_transform(segment_data)

print(scaled_data[:5])

wcss = []

for i in range(1,11):
    kmeans = KMeans(
        n_clusters=i,
        random_state=42,
        n_init=10
    )

    kmeans.fit(scaled_data)

    wcss.append(kmeans.inertia_)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(range(1,11), wcss, marker='o')

plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")

plt.show()

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

df["Cluster"] = kmeans.fit_predict(scaled_data)

df.head()

df["Cluster"].value_counts()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df,
    x="MonthlyCharges",
    y="TotalCharges",
    hue="Cluster",
    palette="Set1"
)

plt.title("Customer Segments")
plt.show()

df.groupby("Cluster")[["tenure","MonthlyCharges","TotalCharges"]].mean()

cluster_churn = df.groupby("Cluster")["Churn"].mean() * 100

print(cluster_churn)

import seaborn as sns
import matplotlib.pyplot as plt

sns.barplot(
    x=cluster_churn.index,
    y=cluster_churn.values-
)

plt.title("Churn Rate by Cluster")
plt.xlabel("Cluster")
plt.ylabel("Churn Percentage")
plt.show()

df.to_csv("customer_segments.csv", index=False)

print("File Saved Successfully")